trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: downloadAppSettings
  displayName: Download appsettings.json file
  inputs:
    secureFile: '$(messengerApiSettingsFile)'
- task: CopyFilesOverSSH@0
  displayName: Publish appsettings file
  inputs:
    sshEndpoint: $(sshServer)
    sourceFolder: $(Agent.TempDirectory)
    contents: '*appsettings.json'
    targetFolder: 'Workspace/Messenger'
    readyTimeout: '20000'